---
# handlers file for vmax_crear_lun
- debug:
    msg: "Ejecutando archivo handlers para el rol vmax_crear_lun"

- name: Add TAGs to vmax_crear_lun
  uri:
    url: "{{ manageiq.api_url }}/api/{{ manageiq.service }}/tags"
    method: POST
    validate_certs: no
    timeout: 200
    headers:
      X-Auth-Token: "{{ manageiq.api_token }}"
      Content-Type:  application/json
    body_format: json
    body:
      action: assign
      resources:
        - category: "senha_ambiente"
          name: "senha_ambiente_desarrollo"
        - category: "senha_Vmax"
          name: "SENHA VMAX Crear Lun"
  ignore_errors: True
     
- name: Add Custom Attributes to vmax_crear_lun
  uri:
    url: "{{ manageiq.api_url }}/api/{{ manageiq.service }}/custom_attributes"
    method: POST
    validate_certs: no
    timeout: 200
    headers:
      X-Auth-Token: "{{ manageiq.api_token }}"
      Content-Type:  application/json
    body_format: json
    body:
      action: add
      resources:
        - name: "Work Order"
          value: "{{ numero_de_ticket  }}"
  ignore_errors: True
...
