---
# tasks file for vmax
# tasks file for vmax_validar_nombre_del_storage_group
#VALIDATION VMAX SRP NAME
- name: "SENHA ::: VMax  ::: Validar nombre del storage group"
  uri:
    url: "https://{{vmax_ip}}:{{vmax_puerto}}/univmax/restapi/84/sloprovisioning/symmetrix/{{vmax_sn}}/storagegroup/{{vmax_storagegroup}}"
#    url: "https://{{vmax_ip}}:{{vmax_puerto}}/univmax/restapi/84/sloprovisioning/symmetrix/{{vmax_sn}}/storagegroup" # Consulta todos los storage groups
    method: GET
    headers:
      Authorization: Basic {{vmax_authorization}}
#    user: "{{ api_user }}"
#    password: "{{ api_pass }}"
    force_basic_auth: yes
    validate_certs: no
    return_content: yes
    follow_redirects: yes
    status_code: 200,201
    timeout: 200
  register: salida_validar_storage_group
  ignore_errors: True
    
- set_fact:
    salida_validar_storage_group_json: "{{ salida_validar_storage_group.json }}"
  when:
    - salida_validar_storage_group.json is defined

- set_fact:
    vmax_espacio_disponible_sg: "{{ salida_validar_storage_group_json.cap_gb }}"
  when:
    - salida_consultar_storage_rp.json is defined

- set_fact:
    vmax_volumenes_actuales_sg: "{{ salida_validar_storage_group_json.num_of_vols }}"
  when:
    - salida_consultar_storage_rp.json is defined

- set_fact:
    vmax_maskingview_sg: "{{ salida_validar_storage_group_json.maskingview[0] }}"
  when:
    - salida_consultar_storage_rp.json is defined
...

