---
# tasks file for vmax
# tasks file for vmax_validar_storage_resource_pool
#VALIDATION VMAX SRP NAME
- name: "SENHA ::: VMax  ::: Validar Storage Resource pool"
  uri:
    url: "https://{{vmax_ip}}:{{vmax_puerto}}/univmax/restapi/84/sloprovisioning/symmetrix/{{vmax_sn}}/srp"
    method: GET
    headers:
      Authorization: Basic {{vmax_authorization}}
#    user: "{{ api_user }}"
#    password: "{{ api_pass }}"
    force_basic_auth: yes
    validate_certs: no
    return_content: yes
    follow_redirects: yes
    status_code: 200,201,500
    timeout: 200
  register: salida_consultar_storage_rp
  ignore_errors: True
  
- set_fact:
    salida_consultar_storage_rp_json: "{{ salida_consultar_storage_rp.json }}"
  when:
    - salida_consultar_storage_rp.json is defined

- set_fact:
    vmax_storage_rp_name: "{{ salida_consultar_storage_rp.json.srpId[0] }}"
  when:
    - salida_consultar_storage_rp.json is defined
...

