---
# tasks file for vmax
# tasks file for vmax_crear_lun
# EXECUTION CREATION OF LUNS
- name: "SENHA ::: VMax  ::: Crear LUN"
  uri:
    url: "https://{{vmax_ip}}:{{vmax_puerto}}/univmax/restapi/sloprovisioning/symmetrix/{{vmax_sn}}/storagegroup/{{vmax_storagegroup}}"
    method: PUT
    headers:
      Authorization: Basic {{vmax_authorization}}
      Content-Type: application/json
      Accept: application/json,version=2
#    user: "{{ api_user }}"
#    password: "{{ api_pass }}"
    body: {"editStorageGroupActionParam": {"expandStorageGroupParam": {"num_of_vols": "{{vmax_num_de_vols}}", "volumeAttribute": {"volume_size": "{{vmax_volume_size}}", "capacityUnit": "{{vmax_capacityUnit}}" }}}}
    body_format: json
    force_basic_auth: yes
    validate_certs: no
    return_content: yes
    follow_redirects: yes
    status_code: 200,201,204,500,400,-1
    timeout: 200
  register: salida_crear_lun
  ignore_errors: True
  
- set_fact:
    salida_crear_lun_json: "{{ salida_crear_lun.json }}"
  when:
    - salida_crear_lun.json is defined
...

