---
# tasks file for vmax
# tasks file for vmax_validar_nombre_del_storage_group
#VALIDATION VMAX SRP NAME
- name: "SENHA ::: VMax  ::: consultar LUNs e IDs existentes"
  uri:
    url: "https://{{vmax_ip}}:{{vmax_puerto}}/univmax/restapi/sloprovisioning/symmetrix/{{vmax_sn}}/volume?storageGroupId={{vmax_storagegroup}}"
    method: GET
    headers:
      Authorization: Basic {{vmax_authorization}}
#    user: "{{ api_user }}"
#    password: "{{ api_pass }}"
    force_basic_auth: yes
    validate_certs: no
    return_content: yes
    follow_redirects: yes
    status_code: 200,201
    timeout: 200
  register: salida_consulta_luns_ids
  ignore_errors: True
    
- set_fact:
    salida_consulta_luns_ids_json: "{{ salida_consulta_luns_ids.json }}"
  when:
    - salida_consulta_luns_ids.json is defined

- set_fact:
    vmax_lista_de_volumenes: 
        - "{{ salida_consulta_luns_ids_json | json_query('resultList.result[*].volumeId') | unique }}"
  when:
    - salida_consulta_luns_ids.json is defined
...

