---
# tasks file for vmax
# Validación de conexión a vmax - Validar End Point
# tasks file for vmax_validar_end_point
- name: "SENHA ::: VMax  ::: Validar vmax End Point"
  uri:
    url: "https://{{vmax_ip}}:{{vmax_puerto}}/univmax/restapi/system/version"
    method: GET
    headers:
      Authorization: Basic {{vmax_authorization}}
#    user: "{{ api_user }}"
#    password: "{{ api_pass }}"
    force_basic_auth: yes
    validate_certs: no
    return_content: yes
    follow_redirects: yes
    status_code: 200,201,500
    timeout: 200
  register: salida_validar_end_point
  ignore_errors: True
  
- set_fact:
    salida_validar_end_point_json: "{{ salida_validar_end_point.json }}"
  when:
    - salida_validar_end_point.json is defined
...
