---
- name: "Definiendo a partir de parametros de entrada la plantilla de la capa presentacion"
  set_fact:
    vmware_template: "{{ gen_plantilla_p_CH }}"
  when: estructura_ambiente.senha_presentacion.vmware_template_presentacion == gen_clave_presentacion1 or estructura_ambiente.senha_presentacion.vmware_template_presentacion == "Plantilla_RHEL_OHS"

- name: "Definiendo a partir de parametros de entrada la plantilla de la capa presentacion"
  set_fact:
    vmware_template: "{{ gen_plantilla_p_CH }}"
  when: estructura_ambiente.senha_presentacion.vmware_template_presentacion == gen_clave_presentacion2 or estructura_ambiente.senha_presentacion.vmware_template_presentacion == "Plantilla_OEL_OHS"

- name: "Definiendo a partir de parametros de entrada la plantilla de la capa presentacion"
  set_fact:
    vmware_template: "{{ gen_plantilla_p_WIN }}"
  when: estructura_ambiente.senha_presentacion.vmware_template_presentacion == gen_clave_presentacion3 or estructura_ambiente.senha_presentacion.vmware_template_presentacion == "Plantilla_WIN_OHS"
    
- name: "Asignacion por defecto capa presentacion"
  set_fact:
    vmware_template: "{{ gen_plantilla_defecto }}"
  when: 
    - estructura_ambiente.senha_presentacion.vmware_template_presentacion != gen_clave_presentacion1 
    - estructura_ambiente.senha_presentacion.vmware_template_presentacion != gen_clave_presentacion2 
    - estructura_ambiente.senha_presentacion.vmware_template_presentacion != gen_clave_presentacion3 

... 
