---
# tasks file for oracle
- set_fact:
    execute_command: "{{oracle_ssh_connect}} export ORACLE_HOME={{oracle_database_sql_oracle_home}} && export ORACLE_SID={{oracle_database_sql_sid}} && {{oracle_database_sqlplus}} -S {{oracle_database_sql_admin_username}}/{{oracle_database_sql_admin_password}} @{{sql_path}}{{guarda_epgcis_senha}} \\\"{{tipo_de_registro}}\\\" \\\"{{clase_de_ci}}\\\" \\\"{{id_de_elemento}}\\\" \\\"{{fecha_de_registro}}\\\" \\\"{{centro_de_datos}}\\\" \\\"{{ambiente}}\\\" \\\"{{capa}}\\\" \\\"{{work_order}}\\\" \\\"{{area_general}}\\\" \\\"{{area_central}}\\\" \\\"{{id_de_servicio}}\\\" \\\"{{id_de_application_profile}}\\\" \\\"{{id_de_aplicacion}}\\\" \\\"{{version_proyecto}}\\\" \\\"{{tenant}}\\\" \\\"{{contrato}}\\\" \\\"{{bridge_domain}}\\\""
  ignore_errors: true

- debug:
    msg: "command: '{{ execute_command }}' Sera ejecutado en sentencia Oracle en el sig esquema ({{ oracle_database_sql_sid }}) (ORACLE_HOME: {{oracle_database_sql_oracle_home }})"
  ignore_errors: true

- name: oracle_persistir_epgcis
  command: "{{execute_command}}"
  register: salida_oracle_persistir_epgcis
  environment:
    ORACLE_HOME: "{{oracle_database_sql_oracle_home}}"
    ORACLE_SID: "{{oracle_database_sql_sid}}"
    SQL_PATH: "{{sql_path}}"
  ignore_errors: true

- set_fact:
    salida_persistir_epgcis: |
      {{salida_oracle_persistir_epgcis.stdout}}
  ignore_errors: true

- set_fact:
    salida_persistir_epgcis_error: |
      {{salida_oracle_persistir_epgcis.stderr}}
  ignore_errors: true

- debug:
    msg: "{{ salida_persistir_epgcis }}"
  ignore_errors: true

- debug:
    msg: "Se prodjo el siguiente error: {{ salida_persistir_epgcis_error }}"
  ignore_errors: true    
...
