- name: "Fecha de inicio proceso F5"
  set_fact:
    f5_fecha_inicio: ansible_date_time.iso8601

- name: Agregar nodo a pool de recursos existentes
  uri:
    url: "https://{{ f5_servidor }}/mgmt/tm/ltm/pool/{{ f5_entrada_nombrepool }}po/members"
    method: POST
    headers:
      Content-Type: "application/json"
      X-F5-Auth-Token: "{{ f5_token }}"
    body: "{\"name\":\"{{f5_entrada_ipnodo}}:{{f5_entrada_puerto}}\",\"address\":\"{{f5_entrada_ipnodo}}\"}"
    body_format: json
    validate_certs: no
    return_content: yes
    follow_redirects: yes
    status_code: 200
  register: f5_resultado_agrega
  ignore_errors: True
  when:
    - f5_existencia_pool == true

- name: "Fecha de inicio proceso F5"
  set_fact:
    f5_fecha_fin: ansible_date_time.iso8601
  when: true == true

- name: "No existe el pool de recusos solicitado"
  set_fact:
    f5_proceso:
      codigo: "02"
      descripcion: "No existe el pool de recusos solicitado"
      instancia: ""
      fecha_inicio: "{{ f5_fecha_inicio }}"
      fecha_fin: "{{ f5_fecha_fin }}"
  when:
    - f5_existencia_pool == false

- name: "Adicion a pool OK de F5"
  set_fact:
    f5_proceso:
      codigo: "99"
      descripcion: "Proceso OK"
      instancia: "{{ f5_resultado_agrega }}"
      fecha_inicio: "{{ f5_fecha_inicio }}"
      fecha_fin: "{{ f5_fecha_fin }}"
  when:
    - f5_resultado_agrega is succeeded
    - f5_existencia_pool == true

- name: "Creacion de pool fallido F5"
  set_fact:
    f5_proceso:
      codigo: "02"
      descripcion: "Proceso fallo"
      instancia: "{{ f5_resultado_agrega }}"
      fecha_inicio: "{{ f5_fecha_inicio }}"
      fecha_fin: "{{ f5_fecha_fin }}"
  when:
    - f5_resultado_agrega is failed
