- set_fact:
    f5_fecha_inicio: ansible_date_time.iso8601    
    
- name: Eliminando NODO
  uri:    
    url: "https://{{ f5_servidor }}/mgmt/tm/ltm/node/{{item}}"
    method: DELETE
    headers:
      Content-Type: "application/json"
      X-F5-Auth-Token: "{{ f5_token }}"
    validate_certs: no
    return_content: yes
    follow_redirects: yes
    status_code: 200
  register: f5_resultado_eliminacion
  ignore_errors: True
  with_items: "{{ f5_entrada_ipsnodos.split(',') }}"
  
    
- set_fact:
    f5_fecha_fin: ansible_date_time.iso8601    

- set_fact:
    f5_proceso:
      codigo: "99"
      descripcion: "Proceso OK"
      instancia: "{{ f5_resultado_eliminacion }}"
      fecha_inicio: "{{ f5_fecha_inicio }}"
      fecha_fin: "{{ f5_fecha_fin }}"
  when: 
    - f5_resultado_eliminacion is succeeded

- set_fact:  
    f5_proceso:
      codigo: "02"
      descripcion: "Proceso fallo no se puede eliminar el nodo dentro del pool {{f5_temporal_ip}}"
      instancia: ""
      fecha_inicio: "{{ f5_fecha_inicio }}"
      fecha_fin: "{{ f5_fecha_fin }}"
  when: 
    - f5_resultado_eliminacion is failed 
