- name: "Eliminar pool de recursos {{ f5_token }}"
  uri:
    url: "https://{{ f5_servidor }}/mgmt/tm/ltm/pool/~{{ f5_particion }}~{{ f5_entrada_nombrepool }}po"
    method: DELETE
    headers:
      Content-Type: "application/json"
      X-F5-Auth-Token: "{{ f5_token }}"
    validate_certs: no
    return_content: yes
    follow_redirects: yes
    status_code: 200
  register: f5_elminacion
  ignore_errors: True
  when:
    - f5_existencia_pool == true

- name:  "Valor en variable {{ f5_entrada_nombrepool }}po"
  command: echo "{{ f5_elminacion }}"
