# @  Author Alan Flores Mendoza
# @  Parametros de entrada 
# vars:
#    f5_entrada_nombrepool: "capa_pres_odi_tcp"
#    f5_entrada_ipnodo: "192.168.10.7"
#    f5_entrada_puerto: "80"
#    f5_entrada_estadonodo: "D"    # H Habilitar o D Deshabilitar
# @  Variables de retorno
#    f5_proceso
# @  Descripcion
# @@ Esta secuencia de metodos realiza la modificacion de un estado en el nodo del recurso solicitado

- name: Ejecutando una sola tarea desde F5/tasks/f5_login.yml
  import_role:
    name: F5
    tasks_from: f5_login
    
- name: Ejecutando una sola tarea desde F5/tasks/f5_validar_pool.yml
  import_role:
    name: F5
    tasks_from: f5_validar_pool

- name: Ejecutando una sola tarea desde F5/tasks/f5_cambiaestado_nodo.yml
  import_role:
    name: F5
    tasks_from: f5_cambiaestado_nodo
