# @  Author Alan Flores Mendoza
# @  Parametros de entrada
# vars:
#    f5_entrada_nombrepool: "capa_pres_odi_tcp"
#    f5_entrada_ipvirtual: "172.10.10.25"
#    f5_entrada_ipsnodos: "192.168.10.8,192.168.10.9"
#    f5_entrada_protocolo: "tcp" # "tcp","udp","http","https","icmp"
#    f5_entrada_puerto: "80"
#    f5_entrada_tipobalanceo: "round-robin" #  "round-robin", o "least-connections-member".
#    f5_entrada_tipopersistencia: "cookie" # dest_addr
# @  Variables de retorno
#    f5_proceso
# @  Descripcion
# @@ Esta secuencia de metodos realiza la creacion de un LB ingresando todos los parametros de entrada mencionados en los renglones primarios

- name: "******************************************************************"
  command: echo "aaaaaaaaaa"

- debug:
    msg: "{{f5_entrada_nombrepool}} {{f5_entrada_ipvirtual}} {{f5_entrada_ipsnodos}} {{f5_entrada_protocolo}} {{f5_entrada_puerto}} {{f5_entrada_tipobalanceo}} {{f5_entrada_tipopersistencia}}"

- name: "SENHA :::  F5 -- Login."
  import_role:
    name: F5
    tasks_from: f5_login

- name: "SENHA :::  F5 -- Validacion de pool."
  import_role:
    name: F5
    tasks_from: f5_validar_pool

- name: "SENHA :::  F5 -- Creacion de pool."
  import_role:
    name: F5
    tasks_from: f5_crear_pool_rest

#- name: "SENHA :::  F5 -- Creacion de cookie."
#  import_role:
#    name: F5
#    tasks_from: f5_crear_cookie

- name: "SENHA :::  F5 -- Creacion de balanceo de carga."
  import_role:
    name: F5
    tasks_from: f5_crear_balanceo
