---
# tasks file for f5_senha_envio_correo
- name: Imprimir resultado
  debug:
    var: f5_resultado

- name: Obtener timestamp del sistema
  shell: "date +%Y%m%d%H%M%S"
  register: fecha_inicio_proceso
  
- name: Tiempo Fin
  command: date +%Y-%m-%d %H:%M:%S
  register: findate
  ignore_errors: True

- set_fact:
    finvariabletiempo: "{{ findate.end[:19] }}"
  when: findate.end != ""

- set_fact:
    nombre_archivo_f5: "{{ numero_de_ticket }}-{{ nombre_aplicacion }}-SEHNAF5CrearBalanceadordeCarga_{{ fecha_inicio_proceso.stdout }}"
  ignore_errors: True
  
- debug:
    msg: "{{ nombre_archivo_f5 }}"

- name: Inicio de archivo HTML
  copy: 
    dest: "/tmp/{{ nombre_archivo_f5 }}.html"
    content: |
            <html>
               <head>
                  <title>Resumen de despliegue</title>
                  <meta charset="UTF-8">
                  <meta name="viewport" content="width=device-width, initial-scale=1">
                  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
                  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
                  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
                  <div class="jumbotron jumbotron-fluid" style="background-color:white;padding-top: 0px;padding-bottom: 0px">
                    <div class="container">
                       <img src="https://drive.google.com/uc?id=1QqaTGiBl0y9HeAlZ_iqyLP21y_YdBbay&export=download" class="img-responsive"> 
                    </div>
                  </div>
               </head>
               <body>
                 <div class="container">
  ignore_errors: True

- name: Creación de tabla Datos Generales y Presentación
  blockinfile:
    path:  "/tmp/{{ nombre_archivo_f5 }}.html"
    marker: ""
    block: |
            <!-- Tabla de contenido -->
                         <table class="table table-striped">
                              <tr>
                                <th style="color:white; background-color:#3C79C2; text-align:center; font-weight: bold" colspan="2">DATOS GENERALES</th>
                              </tr>
                              <tr>
                                 <td>Número de ticket:  </td>
                                 <td> {{ estructura_ambiente.senha_generales.numero_de_ticket }} </td>
                              </tr>
                              <tr>
                                 <td>Nombre del solicitante:  </td>
                                 <td> {{ estructura_ambiente.senha_generales.nombre_solicitante }} </td>
                              </tr>
                              <tr>
                                 <td>Correo del solicitante:  </td>
                                 <td> {{ estructura_ambiente.senha_generales.correo_solicitante }} </td>
                              </tr>
                              <tr>
                                 <td>Centro de datos:  </td>
                                 <td> {{ estructura_ambiente.senha_generales.centro_datos_sat }} </td>
                              </tr>
                              <tr>
                                 <td>Ambiente:  </td>
                                 <td> {{ estructura_ambiente.senha_generales.selector_de_ambiente }} </td>
                              </tr>
                              <tr>
                                 <td>Nombre de la aplicación:  </td>
                                 <td> {{ estructura_ambiente.senha_generales.nombre_aplicacion }} </td>
                              </tr>
                              <tr>
                                 <td>Versión de la aplicación:  </td>
                                 <td> {{ estructura_ambiente.senha_generales.version_proyecto }} </td>
                              </tr>
                              <tr>
                                 <td>Fecha de creación de servicio:  </td>
                                 <td> {{ estructura_ambiente.senha_generales.fecha_inicio_proceso }} </td>
                              </tr>
                              <tr>
                                 <td>Fecha de término de despliegue:  </td>
                                 <td> {{ finvariabletiempo }} </td>
                              </tr>                          
                         </table>
                         <table class="table table-striped">
                              <tr>
                                <th style="color:white; background-color:#3C79C2; text-align:center; font-weight: bold" colspan="3">CAPA DE PRESENTACIÓN</th>
                              </tr>
                            <tr>
                               <td style="vertical-align:middle; text-align:center" rowspan="7">Balanceador</td>
                               <td style="color:white; background-color:#A4A4A4; text-align:center; font-weight: bold" colspan="2">{{ f5_entrada_nombrepool }}</td>
                            </tr>
                            <tr>
                               <td> VIP:  </td>
                               <td> {{ f5_entrada_ipvirtual }} </td>
                            </tr>
                            <tr>
                               <td> Puerto:  </td>
                               <td> {{ f5_entrada_puerto }} </td>
                            </tr>
                            <tr>
                               <td> IPs de nodos:  </td>
                               <td> {{ f5_entrada_ipsnodos }} </td>
                            </tr>
                            <tr>
                               <td> Protocolo:  </td>
                               <td> {{ f5_entrada_protocolo }} </td>
                            </tr>
                            <tr>
                               <td> Tipo de balanceo:  </td>
                               <td> {{ f5_entrada_tipobalanceo }} </td>
                            </tr>
                            <tr>
                               <td> Tipo de persistencia:  </td>
                               <td> {{ f5_entrada_tipopersistencia }} </td>
                            </tr>                         
                         </table>
  when:
    - f5_resultado is succeeded
    - f5_creacion_pool == true
    - f5_existencia_pool == false
  ignore_errors: True
  
- set_fact:
    error_flujo_general: " Proceso FALLIDO por duplicidad en el nombre del pool."                     
  when:
    - f5_resultado is failed or f5_creacion_pool == false or f5_existencia_pool == true
  ignore_errors: True 
   
- name: Final de archivo HTML
  blockinfile:
    path: "/tmp/{{ nombre_archivo_f5 }}.html"
    marker: ""
    block: |
        <!-- final de archivo-->
                </div>
              </body>
          </html>
  ignore_errors: True      
        
- name: Tarea de envio de correo del proceso
  import_role:
    name: general
    tasks_from: general_enviocorreo
  vars:
    general_correo_de: "senha.notificacion@gmail.com"
    general_correo_para: "{{ correo_solicitante }}"
    general_correo_concopia: "{{ lista_correo_electronico }}"
    general_correo_asunto: Folio {{ numero_de_ticket }} - Despliegue Completado - SEHNA F5 Crear Balanceador de Carga
    general_correo_cuerpo: | 
                            <br/>Datos generales del despliegue con el folio <b>{{ numero_de_ticket }}</b>:
                            <br/>
                            <ul>
                            <li>Item desplegado: <b>SEHNA F5 Crear Balanceador de Carga</b></li>
                            <li>Solicitante / Correo:  <b>{{ nombre_solicitante }}</b> / <b>{{ correo_solicitante }}</b></li>
                            <li>Aplicaci&oacute;n / Versi&oacute;n: <b>{{ estructura_ambiente.senha_generales.nombre_aplicacion }}</b> / <b>{{ version_proyecto }}</b> </li>
                            <li>Ambiente: <b>{{ estructura_ambiente.senha_generales.selector_de_ambiente }}</b></li>
                            <li>Estado de desplliegue: <b>Exitoso</b></li>
                            </ul>
                            <br/>
                            <br/>Documentos anexos
                            <ul>
                            <li>Documento detalle de elementos desplegados HTML: <b>{{ nombre_archivo_f5 }}.html</b></li>
                            </ul>                                                                                                                       
    general_correo_adjuntos: "/tmp/{{ nombre_archivo_f5 }}.html"
  when:
    - f5_resultado is succeeded
    - f5_creacion_pool == true
    - f5_existencia_pool == false    
  ignore_errors: True
  
- name: Tarea de envio de correo del proceso escenario fallido
  import_role:
    name: general
    tasks_from: general_enviocorreo
  vars:
    general_correo_de: "senha.notificacion@gmail.com"
    general_correo_para: "{{ correo_solicitante }}"
    general_correo_concopia: "{{ lista_correo_electronico }}"
    general_correo_asunto: Folio {{ numero_de_ticket }} - Despliegue Fallido - SEHNA F5 Crear Balanceador de Carga
    general_correo_cuerpo: | 
                            <br/>Datos generales del despliegue con el folio <b>{{ numero_de_ticket }}</b>:
                            <br/>
                            <ul>
                            <li>Item desplegado: <b>SEHNA F5 Crear Balanceador de Carga</b></li>
                            <li>Solicitante / Correo:  <b>{{ nombre_solicitante }}</b> / <b>{{ correo_solicitante }}</b></li>
                            <li>Aplicaci&oacute;n / Versi&oacute;n: <b>{{ nombre_aplicacion }}</b> / <b>{{ version_proyecto }}</b> </li>
                             <li>Ambiente: <b>{{ estructura_ambiente.senha_generales.selector_de_ambiente }}</b></li>
                            <li>Estado de despliegue: <b>Fallido</b></li>
                            </ul>
                            <br/>
                            <br/>Mensaje de error:
                            <ul>
                            <li>{{ error_flujo_general }}</li>
                            </ul>                                                                                                                      
  when:
    - f5_resultado is failed or f5_creacion_pool == false or f5_existencia_pool == true
...
