---
- name: Obteniendo la informacion de token para posteriores llamados
  uri:
    url: "https://10.20.0.65/api/service_catalogs?expand=resources,service_templates"
    method: GET
  register: manageIQ_resultado
  ignore_errors: True
  degug: manageIQ_resultado
