---
- name: Obtener datos ManageIQ por curl
  shell: 'curl --user admin:smartvm -i -k -X GET -H "Accept: application/json" https://10.20.0.65/api/auth?requester_type=ui'
  register: token

- name: "Obtencion de los catalogos y sus items de servicio de ManageIQ"
  uri:
    url: "https://10.20.0.65/api/auth"
    method: GET
    user: "generico"
    password: "redhat"
    validate_certs: false
    body_format: json
  register: manageIQ_resultado

- debug:
    msg: manageIQ_resultado
