---
- name: Obtener datos ManageIQ por curl
  shell: 'curl --user admin:smartvm -i -k -X GET -H "Accept: application/json" https://10.20.0.65/api/auth?requester_type=ui'
  register: token

#- debug:
#    msg: "{{ token }}"

- name: "Obtencion de los catalogos y sus items de servicio de ManageIQ"
  uri:
    url: "https://10.20.0.65/api/auth"
    method: GET
    user: "generico"
    password: "redhat"
    validate_certs: false
    body_format: json
  register: manageIQ_resultado

- debug:
    msg: "{{ manageIQ_resultado.json.auth_token }}"

- name: "Obtener catalogo de servicios"
  uri:
    url: "https://10.20.0.65/api/service_catalogs?expand=resources,service_templates"
    method: GET
    validate_certs: false
    body_format: json
    headers:
      X-Auth-Token: "{{ manageIQ_resultado.json.auth_token }}"
      Content-Type: "application/json"
    return_content: yes
  register: catalogo_servicios

- name: "Obtener servicios desplegados por service_request"
  uri:
    url: "https://10.20.0.65/api/services?expand=resources"
    method: GET
    validate_certs: false
    body_format: json
    headers:
      X-Auth-Token: "{{ manageIQ_resultado.json.auth_token }}"
      Content-Type: "application/json"
    return_content: yes
  register: servicios_activos

- name: crear arreglo de catalogos
  set_fact: catalogos=[]

- name: "Display all name busqueda de item por catalogo"
  set_fact: catalogos= "{{ item }}"
  with_items: "{{ info_servicio_reg.json.resources }}"

- name: Impresion en consola de catalogos.
  debug:
    msg: "{{ catalogos }}"
