---
- name: "Obtencion de los catalogos y sus items de servicio de ManageIQ"
  uri:
    url: "https://10.20.0.65/api/auth"
    method: GET
    user: "admin"
    password: "smartvm"
    validate_certs: false
    body_format: json
  register: manageIQ_resultado

- debug:
    msg: manageIQ_resultado
