---
- name: Llamado de manageIQ resultado
  uri:
    url: "https://10.20.0.65/api/service_catalogs?expand=resources,service_templates"
    method: GET
    validate_certs: no
    return_content: yes
    follow_redirects: yes
    status_code: 200
  register: manageIQ_resultado
  ignore_errors: True
  degug: manageIQ_resultado
