 
- hosts: localhost
  vars:
    f5_entrada_nombrepool: "balanceo_amara"
    f5_entrada_puerto: "80"

  tasks:

    - name: Ejecutando una sola tarea desde F5/tasks/f5_login.yml
      import_role:
        name: F5
        tasks_from: f5_login
        
    - name: Ejecutando una sola tarea desde F5/tasks/f5_validar_pool.yml
      import_role:
        name: F5
        tasks_from: f5_validar_pool  
  
    - name: Ejecutando una sola tarea desde F5/tasks/f5_eliminar_pool.yml
      import_role:
        name: F5
        tasks_from: f5_eliminar_pool

        