---
- hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - name: Print some debug information 
      vars: 
        declared_variables: |
            Module Variables ("vars"):
            --------------------------------
            {{ vars | to_nice_json }}

            Environment Variables ("environment"):
            --------------------------------
            {{ environment | to_nice_json }} 

            GROUP NAMES Variables ("group_names"):
            --------------------------------
            {{ group_names | to_nice_json }}

            GROUPS Variables ("groups"):
            --------------------------------
            {{ groups | to_nice_json }}

            HOST Variables ("hostvars"):
            --------------------------------
            {{ hostvars | to_nice_json }} 
      debug: 
        msg: "{{ declared_variables.split('\n')}}"
      tags: debug_info
    - name: Imprimir numero de ticket
      debug:
        msg: El numero de ticket es "{{ numero_de_ticket }}"
