---
- name: "Obtencion de los catalogos y sus items de servicio de ManageIQ"
  uri:
    url: "https://10.20.0.65/api/service_catalogs?expand=resources,service_templates"
    method: GET
    validate_certs: false
    body_format: json
    return_content: yes
  register: manageIQ_resultado
    
- debug:
    msg: "{{ manageIQ_resultado }}"
