---
- name: variable manageiq
  debug: var=manageiq.api_url

- name: manageiq.api_token
  debug: var=manageiq.api_token

- name: var=manageiq.service
  debug: var=manageiq.service

- name: var=manageiq.event_target
  debug: var=manageiq.event_target
