---
- name: variable manageiq
  debug: var=manageiq.api_url

- name: manageiq.api_token
  debug: var=manageiq.api_token

- name: var=manageiq.service
  debug: var=manageiq.service

- name: var=manageiq.vms
  debug: var=manageiq.vms

- name: var=manageiq.service_catalogs
  debug: var=manageiq.service_catalogs

- name: var=manageiq.service_dialogs
  debug: var=manageiq.service_dialogs

- name: var=manageiq.tasks pruebas de Israel
  debug: var=manageiq.tasks
