---
- hosts: localhost
  connection: local
  vars:
    log_bucket:
        bucket_name: redhat_test

  tasks:
  - debug: var=manageiq.api_url
  - debug: var=manageiq.api_token
  - debug: var=manageiq.service
  - debug: var=manageiq.event_target
