---
# tasks file for oracle
- set_fact:
    execute_command: "{{oracle_ssh_connect}} export ORACLE_HOME={{oracle_database_sql_oracle_home}} && export ORACLE_SID={{oracle_database_sql_sid}} && {{oracle_database_sqlplus}} -S {{oracle_database_sql_admin_username}}/{{oracle_database_sql_admin_password}} @{{sql_path}}{{guarda_serviciocis_senha}} \\\"{{tipo_de_registro}}\\\" \\\"{{clase_de_ci}}\\\" \\\"{{id_de_elemento}}\\\" \\\"{{fecha_de_registro}}\\\" \\\"{{centro_de_datos}}\\\" \\\"{{ambiente}}\\\" \\\"{{work_order}}\\\" \\\"{{area_general}}\\\" \\\"{{area_central}}\\\" \\\"{{id_de_aplicacion}}\\\" \\\"{{version_de_aplicacion}}\\\" \\\"{{tipo_de_servicio}}\\\""

- debug:
    msg: "command: '{{ execute_command }}' Sera ejecutado en sentencia Oracle en el sig esquema ({{ oracle_database_sql_sid }}) (ORACLE_HOME: {{oracle_database_sql_oracle_home }})"

- name: persistir_servicios_datoscis
  command: "{{execute_command}}"

  register: salida_persistir_servicios_datoscis
  environment:
    ORACLE_HOME: "{{oracle_database_sql_oracle_home}}"
    ORACLE_SID: "{{oracle_database_sql_sid}}"
    SQL_PATH: "{{sql_path}}"
    
- set_fact:
    codigo_aplicacion: |
      {{salida_persistir_servicios_datoscis.stdout}}

- set_fact:
    codigo_aplicacion_error: |
      {{salida_persistir_servicios_datoscis.stderr}}

- debug:
    msg: "{{ codigo_aplicacion }}"
    
- debug:
    msg: "Se prodjo el siguiente error: {{ codigo_aplicacion_error}}"
...
