---
- hosts: localhost
  gather_facts: true
  connection: local
  tasks:
    - uri:
        url: https://iam.amazonaws.com/?Action=GetUser&UserName=kevin-rh&Version=2010-05-08
        return_content: yes
      register: token_response

    - debug: var=token_response.content
...
